#!/usr/bin/env python3
"""Generate the standalone navigator's small 1-bit Noto Sans subset.

Uses the repository's OFL-licensed source font. This does not regenerate reader
font IDs or link the reader font engine into the standalone navigator image.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

root=Path(__file__).resolve().parents[2]
source=root/'lib/EpdFont/builtinFonts/source/NotoSans/NotoSans-Regular.ttf'
output=root/'src/spikes/navigator/NavFontData.h'
lines=['// Generated by tools/walkmap/build_nav_font.py. Do not edit.',
       '// Source: Noto Sans Regular, SIL OFL (lib/EpdFont/builtinFonts/source/NotoSans/OFL.txt).',
       '#pragma once','#include <cstdint>','namespace navigator {',
       'struct NavGlyph { uint16_t offset; uint8_t width, height, advance; int8_t x, y; };',
       'struct NavFont { const NavGlyph* glyphs; const uint8_t* data; uint8_t height; };']
for size in (14,18,22,26,34):
    font=ImageFont.truetype(str(source),size)
    capTop=font.getbbox('H')[1]
    data=bytearray();glyphs=[]
    for ch in map(chr,range(32,127)):
        left,top,right,bottom=font.getbbox(ch)
        width,height=right-left,bottom-top
        glyphs.append((len(data),width,height,round(font.getlength(ch)),left,top-capTop))
        if width and height:
            image=Image.new('L',(width,height))
            ImageDraw.Draw(image).text((-left,-top),ch,font=font,fill=255)
            for y in range(height):
                for x in range(0,width,8):
                    bits=0
                    for bit in range(8):
                        if x+bit<width and image.getpixel((x+bit,y))>=128:bits|=0x80>>bit
                    data.append(bits)
    assert len(data)<65536
    lines.append(f'static constexpr uint8_t navFont{size}Data[] = {{')
    lines += [','.join(str(v) for v in data[i:i+24])+',' for i in range(0,len(data),24)]
    lines.append('};')
    lines.append(f'static constexpr NavGlyph navFont{size}Glyphs[] = {{')
    lines += ['{'+','.join(map(str,g))+'},' for g in glyphs]
    lines += ['};',f'static constexpr NavFont navFont{size}{{navFont{size}Glyphs,navFont{size}Data,{size}}};']
lines.append('} // namespace navigator')
output.write_text('\n'.join(lines)+'\n')
print(output)
