#pragma once

#include <cstddef>
#include <cstdint>

namespace dashboard::v3 {

// Append-only quote table, mirroring Sources/DashboardCore/DashboardV3Quotes.swift
// in the iOS repository entry for entry. That Swift table is the source of
// truth for the ordering, and `scripts/validate_dashboard_v3_quotes.py
// --firmware` in that repository compares the two tables id by id.
//
// The BLE package carries a quote id, not the text, so the two tables must stay
// byte-for-byte ordered forever: inserting or reordering an entry silently
// changes what an already-sent package renders. New quotes go at the end of
// both tables.
//
// Ids are **zero based**, because the phone computes them as
// `dayNumber % quotes.count`. There is deliberately no "no quote" sentinel: id 0
// is the first quote, and a package that never carried a real id still renders a
// valid one rather than an empty footer.
//
// A full year: 365 entries, so a local day only repeats after a year. The table
// is `static constexpr`, which keeps it in flash instead of copying it into
// DRAM. Non-ASCII bytes are written as explicit UTF-8 `\xNN` escapes, like the
// rest of the firmware's Dutch text.

struct Quote {
  const char* text;
  const char* author;
};

static constexpr Quote kQuotes[] = {
    {"Verbeelding is belangrijker dan kennis.", "Albert Einstein"},
    {"Eenvoud is de ultieme verfijning.", "Leonardo da Vinci"},
    {"Minder is meer.", "Ludwig Mies van der Rohe"},
    {"Pluk de dag.", "Horatius"},
    {"Geluk is waar voorbereiding en kans elkaar ontmoeten.", "Seneca"},
    {"Een reis van duizend mijl begint met \xc3\xa9\xc3\xa9n stap.", "Laozi"},
    {"Wie niet waagt, die niet wint.", "Nederlands spreekwoord"},
    {"Kennis spreekt, maar wijsheid luistert.", "Jimi Hendrix"},
    {"Attention is the rarest gift you can give.", "Anonymous"},
    {"An apple a day keeps the doctor away.", "English proverb"},
    {"De aanhouder wint.", "Nederlands spreekwoord"},
    {"Een goed woord vindt een goede plaats.", "Nederlands spreekwoord"},
    {"Nothing grows faster for being hurried.", "Anonymous"},
    {"Slow down to see what you keep missing.", "Anonymous"},
    {"Een dag zonder nieuwsgierigheid is een dag zonder groei.", "Onbekend"},
    {"A watched pot never boils.", "English proverb"},
    {"Te veel verwachten is de kortste weg naar teleurstelling.", "Onbekend"},
    {"Een omweg leert je de buurt kennen.", "Onbekend"},
    {"Ask for the truth and thank the messenger.", "Anonymous"},
    {"Een eigen tempo brengt je verder dan gehaast.", "Onbekend"},
    {"Vele kleintjes maken een grote.", "Nederlands spreekwoord"},
    {"Een goed gesprek begint met een open deur.", "Onbekend"},
    {"If it takes two minutes, do it now.", "Anonymous"},
    {"Een kleine vriendelijkheid werkt nog dagen door.", "Onbekend"},
    {"Let sleeping dogs lie.", "English proverb"},
    {"Learn one new word a day and use it.", "Anonymous"},
    {"Een klein gebaar kan een grote dag maken.", "Onbekend"},
    {"Je best doen is genoeg, verontschuldig je niet.", "Onbekend"},
    {"Een ezel stoot zich geen tweemaal aan dezelfde steen.", "Nederlands spreekwoord"},
    {"Bezint eer ge begint.", "Nederlands spreekwoord"},
    {"Actions speak louder than words.", "English proverb"},
    {"Luisteren levert meer op dan je verwacht.", "Onbekend"},
    {"You can't judge a book by its cover.", "English proverb"},
    {"The habit is the goal.", "Anonymous"},
    {"Kleine potjes hebben grote oren.", "Nederlands spreekwoord"},
    {"Zoek je eigen antwoorden, daar leer je het meest van.", "Onbekend"},
    {"Bescherm je rust, je verdraagt dan meer.", "Onbekend"},
    {"Honesty is the best policy.", "English proverb"},
    {"Ask, then be quiet.", "Anonymous"},
    {"Mededogen is een spier die je kunt trainen.", "Onbekend"},
    {"Regret is a teacher, not a roommate.", "Anonymous"},
    {"Niets doen is ook een beslissing.", "Onbekend"},
    {"Time heals all wounds.", "English proverb"},
    {"The best things in life are free.", "English proverb"},
    {"A good question is half the answer.", "Anonymous"},
    {"The grass is always greener on the other side.", "English proverb"},
    {"Eerlijk duurt het langst.", "Nederlands spreekwoord"},
    {"Benoem je angst en hij wordt kleiner.", "Onbekend"},
    {"The best apology is a changed habit.", "Anonymous"},
    {"Begin at once to live, and count each day as a life.", "Seneca"},
    {"Boredom is often a door, not a wall.", "Anonymous"},
    {"Begin met wat je uitstelt, dan laat het je los.", "Onbekend"},
    {"Beter een goede buur dan een verre vriend.", "Nederlands spreekwoord"},
    {"Een mens heeft weinig nodig om tevreden te zijn.", "Onbekend"},
    {"Fouten erkennen kan altijd nog.", "Onbekend"},
    {"Trade one excuse for one small action.", "Anonymous"},
    {"Give your best hours to your best work.", "Anonymous"},
    {"Haast is een slechte reisgenoot.", "Onbekend"},
    {"He who has a why to live can bear almost any how.", "Friedrich Nietzsche"},
    {"The greatest remedy for anger is delay.", "Seneca"},
    {"Ken je verhaal, dan kun je het herschrijven.", "Onbekend"},
    {"Still waters run deep.", "English proverb"},
    {"Kindness costs nothing.", "English proverb"},
    {"Every cloud has a silver lining.", "English proverb"},
    {"Zeg nooit nooit.", "Nederlands spreekwoord"},
    {"Schrijf je gedachten op en ze worden helderder.", "Onbekend"},
    {"Toegeven houdt vriendschappen heel.", "Onbekend"},
    {"Wat de boer niet kent, dat eet hij niet.", "Nederlands spreekwoord"},
    {"You can lead a horse to water, but not make it drink.", "English proverb"},
    {"Laughter is the best medicine.", "English proverb"},
    {"Better a quiet truth than a loud guess.", "Anonymous"},
    {"Wat je liefdevol doet, doe je beter.", "Onbekend"},
    {"The proof of the pudding is in the eating.", "English proverb"},
    {"Een goed begin is een kwestie van beginnen.", "Onbekend"},
    {"Honger maakt rauwe bonen zoet.", "Nederlands spreekwoord"},
    {"Nothing worth having arrives all at once.", "Anonymous"},
    {"Two heads are better than one.", "English proverb"},
    {"Small kindnesses compound like interest.", "Anonymous"},
    {"Niet geschoten is altijd mis.", "Nederlands spreekwoord"},
    {"Er is geen koe zo bont, of er zit wel een vlekje aan.", "Nederlands spreekwoord"},
    {"A chain is only as strong as its weakest link.", "English proverb"},
    {"Look before you leap.", "English proverb"},
    {"Every dog has its day.", "English proverb"},
    {"Read the instructions, then do it your way.", "Anonymous"},
    {"Een ongeluk komt zelden alleen.", "Nederlands spreekwoord"},
    {"Stel je woede uit en je kiest betere woorden.", "Onbekend"},
    {"Rest is part of the work, not a break from it.", "Anonymous"},
    {"Wie niets doet, doet zelden iets fout.", "Onbekend"},
    {"Een mening herzien is geen zwakte maar scherpte.", "Onbekend"},
    {"Time waits for no one.", "English proverb"},
    {"Wat je niet weet, deert je niet.", "Nederlands spreekwoord"},
    {"Write it down, your memory is a poor accountant.", "Anonymous"},
    {"Choose the slower route sometimes.", "Anonymous"},
    {"Wie zijn fouten herhaalt, leert te laat.", "Onbekend"},
    {"De leugen is snel, de waarheid achterhaalt haar wel.", "Nederlands spreekwoord"},
    {"Keep a light on for the next person.", "Anonymous"},
    {"A stitch in time saves nine.", "English proverb"},
    {"Your calendar tells the truth about your priorities.", "Anonymous"},
    {"Wie het laatst lacht, lacht het best.", "Nederlands spreekwoord"},
    {"Everything flows.", "Heraclitus"},
    {"Practice being early.", "Anonymous"},
    {"Wie goed doet, goed ontmoet.", "Nederlands spreekwoord"},
    {"Open oren maken een lange uitleg overbodig.", "Onbekend"},
    {"Roddelen kost tijd en levert leegte op.", "Onbekend"},
    {"Share the credit and keep the lesson.", "Anonymous"},
    {"Wat je aandacht geeft, groeit.", "Onbekend"},
    {"Out of sight, out of mind.", "English proverb"},
    {"Steek je hand uit, er komt meestal een hand terug.", "Onbekend"},
    {"Vaar je eigen koers, dan maakt de wind niet uit.", "Onbekend"},
    {"Enough is as good as a feast.", "English proverb"},
    {"Een mens wordt rijker van wat hij weggeeft.", "Onbekend"},
    {"Nobody remembers the hurry, only the harm.", "Anonymous"},
    {"Spaar je woorden, je hebt ze nodig als het telt.", "Onbekend"},
    {"Finish one thing before starting the next.", "Anonymous"},
    {"Do the next small thing well.", "Anonymous"},
    {"Twijfel toelaten maakt je denken scherper.", "Onbekend"},
    {"Necessity is the mother of invention.", "English proverb"},
    {"Verandering van spijs doet eten.", "Nederlands spreekwoord"},
    {"Curiosity is cheaper than regret.", "Anonymous"},
    {"Wat langzaam groeit, houdt langer stand.", "Onbekend"},
    {"The squeaky wheel gets the grease.", "English proverb"},
    {"Een wandeling op tijd doet meer dan een pil.", "Onbekend"},
    {"Ga je eigen weg, dan verdwaal je zelden.", "Onbekend"},
    {"Geduld is meer waard dan een schep verstand.", "Onbekend"},
    {"Hope springs eternal.", "English proverb"},
    {"Nieuwsgierigheid houdt verveling op afstand.", "Onbekend"},
    {"Een nieuw begin vraagt een eerste stap, geen heel plan.", "Onbekend"},
    {"Sleeping on it is a decision-making tool.", "Anonymous"},
    {"Een plezier dat je deelt, wordt twee keer zo groot.", "Onbekend"},
    {"We suffer more in imagination than in reality.", "Seneca"},
    {"Durf je fouten te delen, daar groeit vertrouwen.", "Onbekend"},
    {"Let your yes be simple.", "Anonymous"},
    {"Wie een kuil graaft voor een ander, valt er zelf in.", "Nederlands spreekwoord"},
    {"Een mens kent zijn kracht pas als het moet.", "Onbekend"},
    {"Doe wel en zie niet om.", "Nederlands spreekwoord"},
    {"Man is the measure of all things.", "Protagoras"},
    {"Een nieuw idee houdt je jong.", "Onbekend"},
    {"Wie het eerst komt, het eerst maalt.", "Nederlands spreekwoord"},
    {"Let the day be ordinary and good.", "Anonymous"},
    {"Listen twice as long as you intend to.", "Anonymous"},
    {"Fortune favours the bold.", "English proverb"},
    {"Een goed verstaander heeft maar een half woord nodig.", "Nederlands spreekwoord"},
    {"Een mens die leest, reist zonder bagage.", "Onbekend"},
    {"A friend in need is a friend indeed.", "English proverb"},
    {"Ask more questions than you answer.", "Anonymous"},
    {"Speak plainly, it is a kindness.", "Anonymous"},
    {"Vaardigheid verdwijnt zonder oefening.", "Onbekend"},
    {"Give people the room you want for yourself.", "Anonymous"},
    {"Een mens zonder verwondering mist zijn richting.", "Onbekend"},
    {"Two wrongs don't make a right.", "English proverb"},
    {"An hour of practice beats a week of plans.", "Anonymous"},
    {"Zonder wrijving geen glans.", "Nederlands spreekwoord"},
    {"Elk huisje heeft zijn kruisje.", "Nederlands spreekwoord"},
    {"Beter een vogel in de hand dan tien in de lucht.", "Nederlands spreekwoord"},
    {"Een dagboek is een spiegel die niet liegt.", "Onbekend"},
    {"Don't bite the hand that feeds you.", "English proverb"},
    {"The best revenge is not to be like your enemy.", "Marcus Aurelius"},
    {"Zonder pijn geen winst.", "Nederlands spreekwoord"},
    {"The early bird catches the worm.", "English proverb"},
    {"Oefening baart kunst.", "Nederlands spreekwoord"},
    {"Rust is geen luxe maar een levensbehoefte.", "Onbekend"},
    {"Do the difficult thing first, the day gets lighter.", "Anonymous"},
    {"Een mens groeit waar hij fouten durft te maken.", "Onbekend"},
    {"The best advice is usually the one you already knew.", "Anonymous"},
    {"Small habits beat big intentions.", "Anonymous"},
    {"Een dag die traag begint, kan snel goed worden.", "Onbekend"},
    {"Wie zijn woorden weegt, wordt zelden te zwaar bevonden.", "Onbekend"},
    {"Vergelijken kost tijd die je niet terugkrijgt.", "Onbekend"},
    {"Van een kale kip kun je niet plukken.", "Nederlands spreekwoord"},
    {"Haste makes waste.", "English proverb"},
    {"Een zwaluw maakt nog geen zomer.", "Nederlands spreekwoord"},
    {"Alle edele zaken zijn even moeilijk als zeldzaam.", "Spinoza"},
    {"Keep a door open for a different idea.", "Anonymous"},
    {"Mistakes are the tuition of a life well lived.", "Anonymous"},
    {"In het land der blinden is eenoog koning.", "Nederlands spreekwoord"},
    {"We are disturbed not by things but by our opinions.", "Epictetus"},
    {"Een opgestoken hand vindt meestal ruimte.", "Onbekend"},
    {"De kruik gaat zo lang te water tot zij barst.", "Nederlands spreekwoord"},
    {"Begin klein en blijf lang.", "Onbekend"},
    {"Houd je handen vrij, er komt nog iets moois.", "Onbekend"},
    {"Strike while the iron is hot.", "English proverb"},
    {"Leave things better than you found them.", "Anonymous"},
    {"Vergeet niet te genieten van wat je al hebt.", "Onbekend"},
    {"Ken je grenzen, dan kun je ze verleggen.", "Onbekend"},
    {"If you feel lost, take one honest step.", "Anonymous"},
    {"Half of courage is simply staying.", "Anonymous"},
    {"Kies je tijd, dan kies je je zorgen.", "Onbekend"},
    {"Walk to think, not only to arrive.", "Anonymous"},
    {"A tidy desk is a quiet invitation.", "Anonymous"},
    {"The right answer often arrives after the third question.", "Anonymous"},
    {"Put the phone down first.", "Anonymous"},
    {"Een goed idee houdt niet van haast.", "Onbekend"},
    {"Do the thing you keep postponing, for ten minutes.", "Anonymous"},
    {"You can't have your cake and eat it.", "English proverb"},
    {"Je eigen schaduw volgen brengt je nergens.", "Onbekend"},
    {"Van uitstel komt afstel.", "Nederlands spreekwoord"},
    {"Waar een wil is, is een weg.", "Nederlands spreekwoord"},
    {"Eat with people when you can.", "Anonymous"},
    {"Een mens leert het meest van wat hij niet zocht.", "Onbekend"},
    {"Leave a little room in every plan.", "Anonymous"},
    {"There is no time like the present.", "English proverb"},
    {"Vele handen maken licht werk.", "Nederlands spreekwoord"},
    {"Beter een klein begin dan een groot plan.", "Onbekend"},
    {"Twijfel uitspreken maakt hem hanteerbaar.", "Onbekend"},
    {"Het bloed kruipt waar het niet gaan kan.", "Nederlands spreekwoord"},
    {"Teach it to know it.", "Anonymous"},
    {"An open window fixes more moods than an argument.", "Anonymous"},
    {"Rome was not built in a day.", "English proverb"},
    {"Zonder eigen weg volg je die van een ander.", "Onbekend"},
    {"Zo gezegd, zo gedaan.", "Nederlands spreekwoord"},
    {"Wat klein begint, kan groot eindigen.", "Onbekend"},
    {"All that glitters is not gold.", "English proverb"},
    {"Ik denk, dus ik ben.", "Ren\xc3\xa9 Descartes"},
    {"Wie met vuur speelt, verbrandt zich.", "Nederlands spreekwoord"},
    {"You are allowed to change your mind.", "Anonymous"},
    {"Slow and steady wins the race.", "English proverb"},
    {"Het verstand komt met de jaren.", "Nederlands spreekwoord"},
    {"While we teach, we learn.", "Seneca"},
    {"Neem je tijd, dan houd je tijd over.", "Onbekend"},
    {"Waste not, want not.", "English proverb"},
    {"A day without laughter is a day wasted.", "Nicolas Chamfort"},
    {"Verdeel je aandacht en je mist de details.", "Onbekend"},
    {"Oost west, thuis best.", "Nederlands spreekwoord"},
    {"Een vraag kost niets en levert vaak alles op.", "Onbekend"},
    {"If you want to be loved, love.", "Seneca"},
    {"Een kleine gewoonte verslaat een groot voornemen.", "Onbekend"},
    {"Zoals het klokje thuis tikt, tikt het nergens.", "Nederlands spreekwoord"},
    {"Een mens lijdt het meest van het lijden dat hij vreest.", "Nederlands spreekwoord"},
    {"Do one kind thing before breakfast.", "Anonymous"},
    {"Compare yourself only with your past self.", "Anonymous"},
    {"Nood breekt wet.", "Nederlands spreekwoord"},
    {"De appel valt niet ver van de boom.", "Nederlands spreekwoord"},
    {"You reap what you sow.", "English proverb"},
    {"Rest first, then decide.", "Anonymous"},
    {"Je eigen licht zoek je vaak te ver.", "Onbekend"},
    {"Misschien is niets geheel waar, en zelfs dat niet.", "Multatuli"},
    {"Nobody is thinking about you as much as you think.", "Anonymous"},
    {"Breathing deeply is free and rarely tried.", "Anonymous"},
    {"If it is not working, change the approach, not the goal.", "Anonymous"},
    {"Een schip op het strand is een baken in zee.", "Nederlands spreekwoord"},
    {"Wachten is geen stilstand als je ondertussen leert.", "Onbekend"},
    {"Keep your word, it costs less than losing it.", "Anonymous"},
    {"Een goed humeur is een halve oplossing.", "Onbekend"},
    {"Say thank you out loud.", "Anonymous"},
    {"Een pauze is geen opgave.", "Onbekend"},
    {"Een mens leert door te doen, niet door te wachten.", "Onbekend"},
    {"Notice the good weather while it lasts.", "Anonymous"},
    {"Know thyself.", "Delphic maxim"},
    {"Een goed begin is het halve werk.", "Nederlands spreekwoord"},
    {"Finish the day with one thing done.", "Anonymous"},
    {"Beter laat dan nooit.", "Nederlands spreekwoord"},
    {"Nieuwe bezems vegen schoon.", "Nederlands spreekwoord"},
    {"Het zijn de kleine dingen die het doen.", "Onbekend"},
    {"Do less, but finish it.", "Anonymous"},
    {"Least said, soonest mended.", "English proverb"},
    {"One step at a time.", "English proverb"},
    {"The unexamined life is not worth living.", "Socrates"},
    {"Tijd krijg je niet, tijd neem je.", "Onbekend"},
    {"Wonder out loud.", "Anonymous"},
    {"Give credit where credit is due.", "English proverb"},
    {"Stel je wensen bij, dan blijven ze haalbaar.", "Onbekend"},
    {"Geld maakt niet gelukkig.", "Nederlands spreekwoord"},
    {"Say the kind thing while it is still useful.", "Anonymous"},
    {"Notice the person who is always early.", "Anonymous"},
    {"Geduld is een schone zaak.", "Nederlands spreekwoord"},
    {"Een goed idee komt zelden op een volle dag.", "Onbekend"},
    {"No man is free who is not master of himself.", "Epictetus"},
    {"Sleep is not laziness, it is maintenance.", "Anonymous"},
    {"Een gewaarschuwd mens telt voor twee.", "Nederlands spreekwoord"},
    {"Move your body to move your mood.", "Anonymous"},
    {"Say no early and be kind later.", "Anonymous"},
    {"Deel je brood, dan heb je nooit te weinig.", "Onbekend"},
    {"Put your phone away at dinner.", "Anonymous"},
    {"A walk outside solves more than a worry inside.", "Anonymous"},
    {"Read one page before you scroll.", "Anonymous"},
    {"A calm sea does not make a skilled sailor.", "English proverb"},
    {"Rust roest.", "Nederlands spreekwoord"},
    {"Stel de vraag, het antwoord komt vanzelf.", "Onbekend"},
    {"Never make a promise in a hurry.", "Anonymous"},
    {"Silence is a question you can answer later.", "Anonymous"},
    {"Als de kat van huis is, dansen de muizen op tafel.", "Nederlands spreekwoord"},
    {"Wie de schoen past, trekke hem aan.", "Nederlands spreekwoord"},
    {"Een mens die twijfelt, is nog aan het denken.", "Onbekend"},
    {"Wat in het vat zit, verzuurt niet.", "Nederlands spreekwoord"},
    {"We do not have a short time, we waste much of it.", "Seneca"},
    {"Geld is een goede dienaar maar een slechte meester.", "Nederlands spreekwoord"},
    {"Alle waar is naar zijn geld.", "Nederlands spreekwoord"},
    {"Say sorry quickly and mean it.", "Anonymous"},
    {"Wie niet horen wil, moet maar voelen.", "Nederlands spreekwoord"},
    {"Keep a little of your day unplanned.", "Anonymous"},
    {"Make peace with an unfinished list.", "Anonymous"},
    {"A calm voice wins more arguments than a loud one.", "Anonymous"},
    {"Een open vraag is een open raam.", "Onbekend"},
    {"Not every thought deserves an audience.", "Anonymous"},
    {"Wat langzaam rijpt, smaakt het beste.", "Onbekend"},
    {"Alle begin is moeilijk.", "Nederlands spreekwoord"},
    {"The pen is mightier than the sword.", "English proverb"},
    {"Learn the names of the people who help you.", "Anonymous"},
    {"Keep your promises small and often.", "Anonymous"},
    {"Try it before you decide you hate it.", "Anonymous"},
    {"Ask for help before you need it.", "Anonymous"},
    {"You rarely regret the kind thing you said.", "Anonymous"},
    {"Show up, especially on the boring days.", "Anonymous"},
    {"Meet je waarde niet aan cijfers.", "Onbekend"},
    {"Don't count your chickens before they hatch.", "English proverb"},
    {"If it matters, make it easy to start.", "Anonymous"},
    {"Zeg waar je grens ligt, dan begrijpt men je.", "Onbekend"},
    {"Look up more often.", "Anonymous"},
    {"Do the small repair before it becomes a big one.", "Anonymous"},
    {"Birds of a feather flock together.", "English proverb"},
    {"De beste stuurlui staan aan wal.", "Nederlands spreekwoord"},
    {"Begin where you are with what you have.", "Anonymous"},
    {"Keep going, the view changes.", "Anonymous"},
    {"Ask what went right, not only what went wrong.", "Anonymous"},
    {"A small apology repairs a long silence.", "Anonymous"},
    {"A rolling stone gathers no moss.", "English proverb"},
    {"Carry less and arrive happier.", "Anonymous"},
    {"Een goed plan is een plan dat begint.", "Onbekend"},
    {"Wat je zacht brengt, blijft langer liggen.", "Onbekend"},
    {"Better safe than sorry.", "English proverb"},
    {"Don't put all your eggs in one basket.", "English proverb"},
    {"Een kleine moeite is vaak een groot gebaar.", "Onbekend"},
    {"The kindest interpretation is usually the cheapest.", "Anonymous"},
    {"Wie zijn billen brandt, moet op de blaren zitten.", "Nederlands spreekwoord"},
    {"Let someone else be right today.", "Anonymous"},
    {"Een goed voorbeeld is een langzame, zekere leraar.", "Onbekend"},
    {"Wie het kleine niet eert, is het grote niet weerd.", "Nederlands spreekwoord"},
    {"Plant the tree today, the shade takes care of itself.", "Anonymous"},
    {"Verleg je grens en er gaat een nieuwe open.", "Onbekend"},
    {"Wat je deelt, raak je niet kwijt.", "Onbekend"},
    {"A short walk, a long thought.", "Anonymous"},
    {"Variety is the spice of life.", "English proverb"},
    {"Patience is a muscle, not a mood.", "Anonymous"},
    {"A calm mind is a clear instrument.", "Anonymous"},
    {"Let the first draft be ugly.", "Anonymous"},
    {"Elke dag moed is meer dan een heldendaad per jaar.", "Onbekend"},
    {"Wat je geeft, komt meestal terug in een andere vorm.", "Onbekend"},
    {"Tijd voor anderen betekent niet tijd tekort.", "Onbekend"},
    {"Nieuwe ronde, nieuwe kansen.", "Nederlands spreekwoord"},
    {"Too many cooks spoil the broth.", "English proverb"},
    {"Do it for the person you will be in ten years.", "Anonymous"},
    {"Hoge bomen vangen veel wind.", "Nederlands spreekwoord"},
    {"Gedeelde tijd telt dubbel.", "Onbekend"},
    {"Een stilte kan een goed antwoord zijn.", "Onbekend"},
    {"Goed gebruik van tijd maakt haast overbodig.", "Onbekend"},
    {"Keep the promises you make to yourself.", "Anonymous"},
    {"Keep a list of what went well.", "Anonymous"},
    {"Wat je vandaag leert, kun je morgen delen.", "Onbekend"},
    {"Keep one thing simple today.", "Anonymous"},
    {"Zachte heelmeesters maken stinkende wonden.", "Nederlands spreekwoord"},
    {"Don't confuse motion with progress.", "Anonymous"},
    {"Start before you feel ready.", "Anonymous"},
    {"Waar rook is, is vuur.", "Nederlands spreekwoord"},
    {"Een mens is nooit te oud om te leren.", "Nederlands spreekwoord"},
    {"Wat je niet opschrijft, vergeet je het snelst.", "Onbekend"},
    {"A plan you can start beats a plan you admire.", "Anonymous"},
    {"Easy come, easy go.", "English proverb"},
    {"Na regen komt zonneschijn.", "Nederlands spreekwoord"},
    {"A good day starts the night before.", "Anonymous"},
    {"Take notes, insight evaporates.", "Anonymous"},
    {"The quietest person in the room often sees the most.", "Anonymous"},
    {"Do it badly at first, then do it better.", "Anonymous"},
    {"Let the last word go.", "Anonymous"},
    {"Be on time as a small act of respect.", "Anonymous"},
    {"The second best time to plant a tree is now.", "English proverb"},
};

static constexpr size_t QUOTE_COUNT = sizeof(kQuotes) / sizeof(kQuotes[0]);

/// Resolves a wire id to its quote, or nullptr when the id points past the table
/// this firmware knows. A newer phone may send an id from a longer table;
/// drawing nothing is better than drawing the wrong quote.
///
/// The parameter is as wide as the format-3 wire field: the table passed 256
/// entries when the id widened from a byte to a little-endian uint16_t, and a
/// format-2 package's byte simply widens into the same parameter.
inline const Quote* quoteForId(const uint16_t quoteId) {
  if (quoteId >= QUOTE_COUNT) return nullptr;
  return &kQuotes[quoteId];
}

}  // namespace dashboard::v3
