#!/usr/bin/env bash
# Regenerates the dashboard widget-grid icon assets from the single manifest.
#
# Both outputs come from src/components/icons/dashboard-icons.txt, whose line
# order defines the on-the-wire iconId. Run this after editing that manifest;
# never hand-edit either generated header.
#
#   dashboardIcons.h      - the Icon structs (via the SDK's gen_icons.py)
#   dashboardIconTable.h  - iconId -> Icon lookup the renderer indexes
#
# Requires rsvg-convert (brew install librsvg) and Pillow.
set -euo pipefail
cd "$(dirname "$0")/.."

MANIFEST=src/components/icons/dashboard-icons.txt
OUT_DIR=src/components/icons

python3 freeink-sdk/libs/assets/Icons/tools/gen_icons.py \
  --manifest "$MANIFEST" \
  --svgdir freeink-sdk/libs/assets/Icons/lucide/icons \
  --sizes 32,48 \
  --out "$OUT_DIR/dashboardIcons.h"

python3 - "$MANIFEST" "$OUT_DIR/dashboardIconTable.h" <<'PY'
import sys
manifest, out = sys.argv[1], sys.argv[2]
aliases = []
for line in open(manifest):
    line = line.strip()
    if not line or line.startswith("#"):
        continue
    aliases.append(line.split("=")[0].strip())

assert len(aliases) <= 64, f"manifest has {len(aliases)} icons, the 7-bit id allows 64"

with open(out, "w") as f:
    f.write("""#pragma once

#include "Icon.h"
#include "dashboardIcons.h"

// Generated by scripts/gen_dashboard_icons.sh from dashboard-icons.txt. Do not edit.
//
// Index is the wire-format iconId: entry 0 is the "no icon" hole and is null, so
// a decoded iconId indexes this directly. Validation bounds iconId to
// MAX_ICON_ID, so a decoded package can never index past the end.

namespace dashboard {

""")
    f.write(f"constexpr size_t DASHBOARD_ICON_COUNT = {len(aliases)};\n\n")
    for size in (32, 48):
        f.write(f"// {size}px variants, indexed by iconId.\n")
        f.write(f"static const freeink::Icon* const DASHBOARD_ICONS_{size}[] = {{\n")
        f.write("    nullptr,  // iconId 0: no icon\n")
        for alias in aliases:
            f.write(f"    &icon_{alias}_{size},\n")
        f.write("};\n\n")
    f.write("""}  // namespace dashboard
""")
print(f"wrote {out}: {len(aliases)} icons")
PY
