// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define LEXENDDECA_8_FONT_ID (914896891)
#define LEXENDDECA_9_FONT_ID (-256684507)
#define LEXENDDECA_10_FONT_ID (1194773887)
#define LEXENDDECA_12_FONT_ID (-1834705648)
#define LEXENDDECA_14_FONT_ID (-1806001351)
#define LEXENDDECA_16_FONT_ID (-2000304501)
#define LEXENDDECA_18_FONT_ID (1302402945)
#define LEXENDDECA_20_FONT_ID (-1459152267)
#define CHAREINK_8_FONT_ID (312370057)
#define CHAREINK_9_FONT_ID (631165824)
#define CHAREINK_10_FONT_ID (-944299713)
#define CHAREINK_12_FONT_ID (562864807)
#define CHAREINK_14_FONT_ID (-1176545950)
#define CHAREINK_16_FONT_ID (-1477679466)
#define CHAREINK_18_FONT_ID (-787708407)
#define CHAREINK_20_FONT_ID (-390579825)
#define BITTER_8_FONT_ID (-1879788067)
#define BITTER_9_FONT_ID (360669977)
#define BITTER_10_FONT_ID (-142408147)
#define BITTER_12_FONT_ID (313087974)
#define BITTER_14_FONT_ID (-76463891)
#define BITTER_16_FONT_ID (-864319200)
#define BITTER_18_FONT_ID (-1308817601)
#define BITTER_20_FONT_ID (1392022129)
#define LEXENDDECA_18_BOLD_DASH_FONT_ID (1901501149)
#define LEXENDDECA_22_BOLD_DASH_FONT_ID (-766020398)
#define LEXENDDECA_28_BOLD_DASH_FONT_ID (1689469529)
#define LEXENDDECA_34_BOLD_DASH_FONT_ID (-445379714)
#define UI_10_FONT_ID (-1313900173)
#define UI_12_FONT_ID (1544960787)
#define SMALL_FONT_ID (1406075677)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(LEXENDDECA_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(CHAREINK_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BITTER_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_18_BOLD_DASH_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_22_BOLD_DASH_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_28_BOLD_DASH_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_34_BOLD_DASH_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
